name: Hello on Push

on: [push]

jobs:
  Hello-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello! Triggered by a ${{ github.event_name }} event."
  Vonjour-GitHub-Actions:
    uses: oginom/github-actions-test/.github/workflows/vonjour_reuse
    with:
      name: Oginom
