name: Hello on Push

on:
  pull_request:
  workflow_call:

jobs:
  Hello-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello! Triggered by a ${{ github.event_name }} event."
      - run: echo "Hello, ${{ secrets.SECRET_NAME }}."
      - run: echo "Hello, ${{ secrets.SECRET_NANA || github.token }}."
      - run: echo "Hello, str contains ll."
        if: ${{ contains(env.secret_str, github.actor) }}
        env:
          secret_str: ${{ secrets.SECRET_STR }}
  Vonjour-GitHub-Actions:
    uses: ./.github/workflows/vonjour_reuse.yml
    with:
      name: Oginom
